# This is a basic workflow to help you get started with Actions

name: Deploy DEV WEB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - next
      - main
    paths:
      - 'apps/web/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_web:
    uses: ./.github/workflows/reusable-web-e2e.yml
    with:
      ee: true
    secrets: inherit

  # This workflow contains a single job called "build"
  deploy_web:
    needs: test_web
    environment: Development
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    uses: ./.github/workflows/reusable-web-deploy.yml
    secrets: inherit
    with:
      react_app_api_url: https://dev.api.novu.co
      react_app_ws_url: https://dev.ws.novu.co
      react_app_webhook_url: https://dev.webhook.novu.co
      react_app_widget_embed_path: https://dev.embed.novu.co/embed.umd.min.js
      react_app_sentry_dsn: https://2b5160da86384949be4cc66679c54e79@o1161119.ingest.sentry.io/6250907
      react_app_environment: dev
      react_app_mail_server_domain: dev.inbound-mail.novu.co
      netlify_deploy_message: Dev deployment
      netlify_alias: dev
      netlify_gh_env: development
      netlify_site_id: 45396446-dc86-4ad6-81e4-86d3eb78d06f

  publish_docker_image_web:
    needs: test_web
    environment: Development
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    uses: ./.github/workflows/reusable-web-docker.yml
    secrets: inherit
    with:
      environment: dev
