name: "Pull Request Labeller"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master

      - uses: microsoft/PR-Metrics@v1.5.3
        name: PR Metrics
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base-size: 200
          growth-rate: 2.0
          test-factor: 0.5
        continue-on-error: true
