name: Build, tag and push docker image to ghcr.io

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      project_path:
        required: true
        type: string
      test_port:
        required: false
        default: '1341'
        type: string
      health_check:
        required: false
        default: false
        type: boolean
      # supported tags: dev, stg, prod
      env_tag:
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reusable_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    outputs:
      docker_image: ${{ steps.build-image.outputs.IMAGE }}
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    strategy:
      matrix:
        name: [ 'novu/${{ inputs.project }}-ee', 'novu/${{ inputs.project }}' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Depot
        uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Build, tag, and push image to ghcr.io
        id: build-image
        if: ${{ inputs.env_tag == 'dev' || inputs.env_tag == 'stg' }}
        env:
          REGISTRY_OWNER: novuhq
          DOCKER_NAME: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
          ENV_TAG: ${{ inputs.env_tag }}
          PROJECT: ${{ inputs.project }}
          PROJECT_PATH: ${{ inputs.project_path }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
          DEPOT_PROJECT_ID: f88777ff6m
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
          depot build --push \
            -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG \
            -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG \
            -f $PROJECT_PATH/Dockerfile .
          echo "IMAGE=ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Production build, tag, and push image to ghcr.io
        id: build-prod-image
        if: ${{ inputs.env_tag == 'prod' }}
        env:
          REGISTRY_OWNER: novuhq
          DOCKER_NAME: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
          ENV_TAG: ${{ inputs.env_tag }}
          PROJECT_PATH: ${{ inputs.project_path }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
          DEPOT_PROJECT_ID: f88777ff6m
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
          depot build --push \
            -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG \
            -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$ENV_TAG \
            -t ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:latest \
            -f $PROJECT_PATH/Dockerfile .
          echo "IMAGE=ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Health check test
        id: health-check
        needs: [build-image, build-prod-image]
        if: ${{ inputs.health_check == 'true' }}
        env:
          REGISTRY_OWNER: novuhq
          DOCKER_NAME: ${{ matrix.name }}
          IMAGE_TAG: ${{ github.sha }}
          TEST_PORT: ${{ inputs.test_port }}
          GH_ACTOR: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
          DEPOT_PROJECT_ID: f88777ff6m
        run: |
          echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin

          docker run --network=host --name $PROJECT -dit --env NODE_ENV=test ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker run --network=host appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:$TEST_PORT/v1/health-check | grep 'ok'
